// THEME
export const FILTER = 'FILTER';
export const CHANGE_HEADER = 'CHANGE_HEADER';
// AUTH
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
// QUINIELA user lists
export const GET_MY_QUINIELAS = 'GET_MY_QUINIELAS';
export const GET_QUINIELA_STRUCTURES = 'GET_QUINIELA_STRUCTURES';
export const GET_ALL_QUINIELAS = 'GET_QUINIELAS';
export const ACCEPT_INVITATION_QUINIELA = 'ACCEPT_INVITATION_QUINIELA';
export const REFUSE_INVITATION_QUINIELA = 'REFUSE_INVITATION_QUINIELA';
export const GET_INVITATION_QUINIELAS = 'GET_INVITATION_QUINIELAS';
export const GET_INVITATION_SENT = 'GET_INVITATION_SENT';
export const GET_INVITATION_ACCEPTED = 'GET_INVITATION_ACCEPTED';
export const GET_INVITATION_REFUSED = 'GET_INVITATION_REFUSED';
export const GET_INVITATION_BY_STATUS = 'GET_INVITATION_BY_STATUS';
export const GET_SUPER_EXIST = 'GET_SUPER_EXIST';
// QUINIELA options
export const POST_QUINIELA = 'POST_QUINIELA';
export const GET_QUINIELA = 'GET_QUINIELA';
export const GET_QUINIELA_ERROR = 'GET_QUINIELA_ERROR';
export const DELETE_QUINIELA = 'DELETE_QUINIELA';
export const GET_QUINIELA_USERS = 'GET_QUINIELA_USERS'; // also positions
export const QUINIELAS_BY_TYPE = 'QUINIELAS_BY_TYPE'; // quartos, final etc.
// QUINIELA Actions
export const POST_INVITE_QUINIELA_USER = 'POST_INVITE_QUINIELA_USER';
export const GET_INVITATIONS_BY_STATE = 'GET_INVITATIONS_BY_STATE'; // (1 aceptadas, 2 pendiente, 3 rechazada)
// GAME options
export const POST_GAME = 'POST_GAME';
export const POST_PREDICTIONS = 'POST_PREDICTIONS';
export const GET_PREDICTIONS = 'GET_PREDICTIONS';
export const GET_QUINIELA_POSITIONS = 'GET_QUINIELA_POSITIONS';
export const GET_GAMES_BY_STRUCTURE = 'GET_GAMES_BY_STRUCTURE';
export const GET_GAME = 'GET_GAME';
export const GET_USER_PREDICTIONS = 'GET_USER_PREDICTIONS';
export const SET_GAME_GRUPOS = 'SET_GAME_GRUPOS';
export const SET_GAME_OCTAVOS = 'SET_GAME_OCTAVOS';
export const SET_GAME_CUARTOS = 'SET_GAME_CUARTOS';
export const SET_GAME_SEMIFINALES = 'SET_GAME_SEMIFINALES';
export const SET_GAME_TERCEROS = 'SET_GAME_TERCEROS';
export const SET_GAME_FINAL = 'SET_GAME_FINAL';

// GAME countries
export const COUNSTRIES_BY_GROUP = 'COUNSTRIES_BY_GROUP';
